name: Build packages
on:
  push:
    branches: [ 
      unstable,
      testing,
      stable,
      main ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
env:
 IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
 BUILDER_TAG: ghcr.io/boukehaarsma23/chimeraos-builder:main
 IMAGE_NAME: bouhaa-os

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:     
  build:
    if: github.event_name != 'pull_request'
    name: Build System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Populate version numbers
        id: version
        run: |
          echo "SHA_HEAD_SHORT=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          docker pull ${{ env.BUILDER_TAG }}
          echo "SHA_BUILDER=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.BUILDER_TAG }})" >> $GITHUB_ENV
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/java
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/az
          df -h
      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}


      # Build image using Buildah action
      - name: Build Image
        uses: Wandalen/wretry.action@v3.5.0
        id: build_image
        with:
          action: redhat-actions/buildah-build@v2
          attempt_limit: 5
          attempt_delay: 15000
          with: |
            containerfiles: ./Containerfile
            image: ${{ env.IMAGE_NAME }}
            labels: |
              org.opencontainers.image.title=${{ env.IMAGE_NAME }}
              org.opencontainers.image.description=Gaming
            extra-args: |
              --isolation chroot
    
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ env.IMAGE_NAME }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust